apiVersion: v1
kind: Service
metadata:
    name: nmishrpipelinesjavascriptdocker2
spec:
    type: LoadBalancer
    ports:
    - port: 8100 
    selector:
        app: nmishrpipelinesjavascriptdocker2
